/**
 * Smart Meal Manager — PDF Report Generation Utility
 * Generates print-ready, professional monthly and bazaar audit reports using jsPDF & autoTable.
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import {
  BazaarExpense,
  DailyMeal,
  Deposit,
  MealUpdateHistoryItem,
  Member,
  Month,
  MonthFinancialSummary,
  UniversalExpense,
} from '../types';
import { formatMeal, formatTakaAscii, roundToTwo } from './calculations';

/**
 * Sanitizes any string destined for standard jsPDF Latin fonts (Helvetica).
 * Eliminates Unicode byte corruption (which turns Bengali glyphs into garbled symbols like ¸¾¬Í¬¿°).
 * If a name has an English component and a Bengali component (e.g. "Sabbir Hossain (সাব্বির)"),
 * it extracts the clean English title/name "Sabbir Hossain".
 * If the string is pure Bengali, it safely transliterates it so it never produces corrupted symbols.
 */
export function cleanForPdf(text: string | null | undefined, fallback = 'N/A'): string {
  if (!text) return fallback;

  // 1. Remove Bengali text inside parentheses, e.g. "Sabbir Hossain (সাব্বির)" -> "Sabbir Hossain"
  let cleaned = text.replace(/\s*\([^)]*[\u0980-\u09FF][^)]*\)/g, '').trim();

  // 2. Remove bracketed Bengali, e.g. "Rent [ভাড়া]" -> "Rent"
  cleaned = cleaned.replace(/\s*\[[^\]]*[\u0980-\u09FF][^\]]*\]/g, '').trim();

  // 3. Remove inline Bengali words if there are also Latin words
  const hasLatin = /[a-zA-Z0-9]/.test(cleaned);
  if (hasLatin) {
    cleaned = cleaned.replace(/[\u0980-\u09FF]+/g, '').replace(/\s+/g, ' ').trim();
  } else if (/[\u0980-\u09FF]/.test(cleaned)) {
    // Pure Bengali text without Latin: map common Bengali phonetic characters
    const bnToEnMap: Record<string, string> = {
      'অ': 'O', 'আ': 'A', 'ই': 'I', 'ঈ': 'I', 'উ': 'U', 'ঊ': 'U', 'ঋ': 'R',
      'এ': 'E', 'ঐ': 'Oi', 'ও': 'O', 'ঔ': 'Ou',
      'ক': 'K', 'খ': 'Kh', 'গ': 'G', 'ঘ': 'Gh', 'ঙ': 'Ng',
      'চ': 'Ch', 'ছ': 'Chh', 'জ': 'J', 'ঝ': 'Jh', 'ঞ': 'N',
      'ট': 'T', 'ঠ': 'Th', 'ড': 'D', 'ঢ': 'Dh', 'ণ': 'N',
      'ত': 'T', 'থ': 'Th', 'দ': 'D', 'ধ': 'Dh', 'ন': 'N',
      'প': 'P', 'ফ': 'F', 'ব': 'B', 'ভ': 'Bh', 'ম': 'M',
      'য': 'Z', 'র': 'R', 'ল': 'L', 'শ': 'Sh', 'ষ': 'Sh', 'স': 'S', 'হ': 'H',
      'ড়': 'R', 'ঢ়': 'Rh', 'য়': 'Y', 'ৎ': 'T',
      'া': 'a', 'ি': 'i', 'ী': 'ee', 'ু': 'u', 'ূ': 'oo', 'ৃ': 'ri',
      'ে': 'e', 'ৈ': 'oi', 'ো': 'o', 'ৌ': 'ou', '্': '', 'ং': 'ng', 'ঃ': '', 'ঁ': '',
      '০': '0', '১': '1', '২': '2', '৩': '3', '৪': '4', '৫': '5', '৬': '6', '৭': '7', '৮': '8', '৯': '9',
    };
    let transliterated = '';
    for (const ch of cleaned) {
      transliterated += bnToEnMap[ch] !== undefined ? bnToEnMap[ch] : (ch.charCodeAt(0) <= 127 ? ch : '');
    }
    cleaned = transliterated.replace(/\s+/g, ' ').trim();
  }

  // 4. Strip out any remaining characters outside standard printable ASCII range
  cleaned = cleaned.replace(/[^\x20-\x7E]/g, '').trim();

  return cleaned || fallback;
}

export function generateMonthlyPDFReport(
  month: Month,
  summary: MonthFinancialSummary,
  members: Member[],
  dailyMeals: DailyMeal[],
  bazaarExpenses: BazaarExpense[],
  universalExpenses: UniversalExpense[],
  deposits: Deposit[],
  mealHistory: MealUpdateHistoryItem[],
  generatedBy: string
): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const dateStr = new Date().toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  // Header Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(30, 41, 59); // Slate 800
  doc.text('Smart Meal Manager - Monthly Financial Report', 40, 45);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // Slate 500
  const safeMonthName = cleanForPdf(month.name, 'Active Month');
  const safeGeneratedBy = cleanForPdf(generatedBy, 'Manager');
  doc.text(`Month: ${safeMonthName} | Period: ${month.startDate} to ${month.endDate}`, 40, 62);
  doc.text(`Generated By: ${safeGeneratedBy} | Date: ${dateStr} | Status: ${month.status.toUpperCase()}`, 40, 76);

  // Divider line
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(1);
  doc.line(40, 86, pageWidth - 40, 86);

  // Overview Summary Cards / Metrics Table
  autoTable(doc, {
    startY: 96,
    theme: 'grid',
    head: [['Total Members', 'Total Meals', 'Meal Rate', 'Total Bazaar', 'Universal Exp', 'Total Deposits', 'Net Status']],
    body: [
      [
        summary.totalMembers.toString(),
        formatMeal(summary.totalMeals),
        formatTakaAscii(summary.mealRate),
        formatTakaAscii(summary.totalGeneralBazaar),
        formatTakaAscii(summary.totalUniversalExpense),
        formatTakaAscii(summary.totalDeposits),
        summary.totalReceivable >= summary.totalPayable
          ? `Surplus: ${formatTakaAscii(summary.totalReceivable - summary.totalPayable)}`
          : `Deficit: ${formatTakaAscii(summary.totalPayable - summary.totalReceivable)}`,
      ],
    ],
    headStyles: {
      fillColor: [15, 118, 110], // Teal 700
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8.5,
      halign: 'center',
    },
    bodyStyles: {
      fontSize: 8.5,
      halign: 'center',
      textColor: [30, 41, 59],
    },
    styles: { cellPadding: 5 },
  });

  // Member Balances Table
  const currentY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 18;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text('Member Balance & Cost Sheet', 40, currentY);

  const memberRows = Object.values(summary.memberSummaries).map((m) => {
    let statusLabel = 'Settled (0.00)';
    if (m.balanceStatus === 'receivable') {
      statusLabel = `Receivable (+${formatTakaAscii(m.finalBalance)})`;
    } else if (m.balanceStatus === 'payable') {
      statusLabel = `Payable (${formatTakaAscii(m.finalBalance)})`;
    }

    return [
      cleanForPdf(m.name, 'Member'),
      formatTakaAscii(m.previousBalance),
      formatMeal(m.totalMeal),
      formatTakaAscii(m.mealCost),
      formatTakaAscii(m.personalBazaarCost),
      formatTakaAscii(m.universalCostShare),
      formatTakaAscii(m.totalCost),
      formatTakaAscii(m.totalDeposit),
      formatTakaAscii(m.finalBalance),
      statusLabel,
    ];
  });

  autoTable(doc, {
    startY: currentY + 8,
    theme: 'striped',
    head: [
      [
        'Member Name',
        'Prev Bal',
        'Meals',
        'Meal Cost',
        'Bazaar Cost',
        'Universal',
        'Total Cost',
        'Total Deposit',
        'Final Balance',
        'Status',
      ],
    ],
    body: memberRows,
    headStyles: {
      fillColor: [30, 41, 59],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8,
    },
    bodyStyles: {
      fontSize: 7.5,
      textColor: [30, 41, 59],
    },
    columnStyles: {
      0: { cellWidth: 'auto', fontStyle: 'bold' },
      8: { fontStyle: 'bold' },
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 8) {
        const val = data.cell.raw as string;
        if (val.startsWith('-')) {
          data.cell.styles.textColor = [220, 38, 38]; // Red
        } else {
          data.cell.styles.textColor = [22, 163, 74]; // Green
        }
      }
    },
  });

  // Footer notes & signature lines
  const finalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 25;
  if (finalY < 750) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      '* Final Balance Formula: Previous Balance + Deposit - Total Cost. Positive (+) means member will receive refund; Negative (-) means member owes due.',
      40,
      finalY
    );

    doc.text('Prepared by: ____________________', 40, finalY + 45);
    doc.text('Audited & Approved by: ____________________', pageWidth - 240, finalY + 45);
  }

  // Save the document
  const safeName = cleanForPdf(month.name, 'Month').replace(/[^a-zA-Z0-9_-]/g, '_');
  doc.save(`SMM_Monthly_Report_${safeName}.pdf`);
}

export function generateBazaarPDFReport(
  month: Month,
  bazaarExpenses: BazaarExpense[],
  universalExpenses: UniversalExpense[],
  members: Member[],
  deposits: Deposit[],
  generatedBy: string
): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const dateStr = new Date().toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  const memberNameMap: Record<string, string> = {};
  for (const m of members) {
    memberNameMap[m.id] = cleanForPdf(m.name, 'Member');
  }

  // Header Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(30, 41, 59);
  doc.text('Smart Meal Manager - Bazaar & Expense Report', 40, 45);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  const safeMonthName = cleanForPdf(month.name, 'Active Month');
  const safeGeneratedBy = cleanForPdf(generatedBy, 'Manager');
  doc.text(`Month: ${safeMonthName} | Period: ${month.startDate} to ${month.endDate}`, 40, 62);
  doc.text(`Generated By: ${safeGeneratedBy} | Date: ${dateStr}`, 40, 76);

  // Divider
  doc.setDrawColor(226, 232, 240);
  doc.line(40, 84, pageWidth - 40, 84);

  // 1. General Bazaar Table
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text('1. General Bazaar Expenses (Personal Bazaar List)', 40, 102);

  const bazaarRows = bazaarExpenses.map((b) => [
    b.date,
    memberNameMap[b.memberId] || 'Unknown',
    cleanForPdf(b.description, 'Bazaar Expense'),
    b.type.replace('_', ' ').toUpperCase(),
    formatTakaAscii(b.amount),
    cleanForPdf(b.createdBy, 'Admin'),
  ]);

  const totalBazaarAmt = bazaarExpenses.reduce((sum, b) => sum + (Number(b.amount) || 0), 0);

  autoTable(doc, {
    startY: 110,
    theme: 'striped',
    head: [['Date', 'Shopper (Member)', 'Description', 'Category', 'Amount', 'Recorded By']],
    body:
      bazaarRows.length > 0
        ? [
            ...bazaarRows,
            ['Total General Bazaar', '', '', '', formatTakaAscii(totalBazaarAmt), ''],
          ]
        : [['No bazaar expenses recorded.', '', '', '', '', '']],
    headStyles: {
      fillColor: [15, 118, 110],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8,
    },
    bodyStyles: { fontSize: 7.5 },
  });

  // 2. Universal Expenses Table
  let nextY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 18;
  if (nextY > 700) {
    doc.addPage();
    nextY = 40;
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text('2. Universal Mess Expenses (Shared Utilities)', 40, nextY);

  const uniRows = universalExpenses.map((u) => [
    u.date,
    cleanForPdf(u.description, 'Utility Bill'),
    `${u.applicableMemberIds.length} Members`,
    formatTakaAscii(u.amount),
    formatTakaAscii(u.perMemberShare),
    cleanForPdf(u.createdBy, 'Admin'),
  ]);

  const totalUniAmt = universalExpenses.reduce((sum, u) => sum + (Number(u.amount) || 0), 0);

  autoTable(doc, {
    startY: nextY + 8,
    theme: 'striped',
    head: [['Date', 'Description', 'Applicable Members', 'Total Amount', 'Per Member Share', 'Recorded By']],
    body:
      uniRows.length > 0
        ? [
            ...uniRows,
            ['Total Universal Expenses', '', '', formatTakaAscii(totalUniAmt), '', ''],
          ]
        : [['No universal expenses recorded.', '', '', '', '', '']],
    headStyles: {
      fillColor: [59, 130, 246],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8,
    },
    bodyStyles: { fontSize: 7.5 },
  });

  // 3. Deposits Summary Table
  let depY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 18;
  if (depY > 700) {
    doc.addPage();
    depY = 40;
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text('3. Member Cash & Digital Deposits (Deposit Ledger)', 40, depY);

  const depRows = deposits.map((d) => [
    d.date,
    memberNameMap[d.memberId] || 'Unknown',
    cleanForPdf(d.note, 'Regular Deposit'),
    formatTakaAscii(d.amount),
    cleanForPdf(d.createdBy, 'Admin'),
  ]);

  const totalDepAmt = deposits.reduce((sum, d) => sum + (Number(d.amount) || 0), 0);

  autoTable(doc, {
    startY: depY + 8,
    theme: 'striped',
    head: [['Date', 'Member', 'Note / Mode', 'Amount', 'Recorded By']],
    body:
      depRows.length > 0
        ? [
            ...depRows,
            ['Total Deposits', '', '', formatTakaAscii(totalDepAmt), ''],
          ]
        : [['No additional deposits recorded.', '', '', '', '']],
    headStyles: {
      fillColor: [100, 116, 139],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8,
    },
    bodyStyles: { fontSize: 7.5 },
  });

  const safeName = cleanForPdf(month.name, 'Month').replace(/[^a-zA-Z0-9_-]/g, '_');
  doc.save(`SMM_Bazaar_Report_${safeName}.pdf`);
}

export function generateMonthlyReportPdf(params: {
  activeMonth: Month;
  financialSummary: MonthFinancialSummary;
  bazaarExpenses?: BazaarExpense[];
  universalExpenses?: UniversalExpense[];
  members?: Member[];
  dailyMeals?: DailyMeal[];
  deposits?: Deposit[];
  mealHistory?: MealUpdateHistoryItem[];
  generatedBy?: string;
}): void {
  generateMonthlyPDFReport(
    params.activeMonth,
    params.financialSummary,
    params.members || [],
    params.dailyMeals || [],
    params.bazaarExpenses || [],
    params.universalExpenses || [],
    params.deposits || [],
    params.mealHistory || [],
    params.generatedBy || 'Admin'
  );
}

export function generateBazaarReportPdf(params: {
  activeMonth: Month;
  bazaarExpenses?: BazaarExpense[];
  universalExpenses?: UniversalExpense[];
  members?: Member[];
  deposits?: Deposit[];
  generatedBy?: string;
}): void {
  generateBazaarPDFReport(
    params.activeMonth,
    params.bazaarExpenses || [],
    params.universalExpenses || [],
    params.members || [],
    params.deposits || [],
    params.generatedBy || 'Admin'
  );
}
